<?php

namespace HexideDigital\HexideAdmin\Console\Commands;

use App\Models\Role;
use App\Models\User;
use Symfony\Component\Console\Input\InputOption;

class CreateAdminUser extends BaseCommand
{
    protected $name = 'hd-admin:create:admin-user';
    protected $description = 'Create new user with admin roles';

    public function handle(): int
    {
        $emailExists = true;
        $first = $this->option('email');
        $email = null;

        while ($emailExists) {
            if ($first) {
                $email = $this->option('email');
                $first = false;
            } else {
                $email = $this->ask('Enter email', $this->option('email') ?? 'admin@admin.com');
            }

            $emailExists = User::where('email', $email)->get()->isNotEmpty();
            if ($emailExists) {
                $this->warn('Email exists, enter another.');

            } else if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                $emailExists = true;
                $this->warn('Email invalid.');
            }
            if ($this->option('no-interaction') && $emailExists) {
                return self::FAILURE;
            }
        }

        $name = $this->option('name');
        if (!empty($name)) {
            $name = $this->ask('Enter name', \Arr::first(explode('@', $email)));
        } else {
            $name = \Arr::first(explode('@', $email));
        }

        $incorrect = !$this->option('generate');
        $generate = $this->option('generate');
        $password = null;

        while ($incorrect) {
            $password = $this->option('password') ?? $this->secret('Enter password (length 4-20 chars, but if empty will be autogenerated)');

            $generate = empty($password);
            if (!$generate) {
                $length_correct = 4 <= strlen($password) && strlen($password) <= 20;
                if ($length_correct) {
                    $confirmPassword = $this->option('password') ?? $this->secret('Confirm password');

                    $incorrect = $confirmPassword !== $password;
                    if ($incorrect) {
                        $this->warn('Invalid confirm password');
                    }
                } else {
                    $this->warn('invalid password length');
                }
            }
        }

        if ($generate) {
            $password = \Str::random(12);
        }

        $user = User::make([
            'name'     => $name,
            'email'    => $email,
            'password' => \Hash::make($password),
        ]);

        if (in_array('is_system', $user->getFillable())) {
            $user->is_system = $email === 'admin@admin.com';
        }

        $user->save();

        $role = Role::firstWhere('key', 'admin');
        $user->roles()->attach($role);

        $this->info('New admin user created');
        $this->table(
            ['field', 'value'],
            [
                ['name', $name],
                ['email', $email],
                ['password', $generate ? $password : '********'],
                ['url', route('admin.login')],
            ]
        );

        return self::SUCCESS;
    }

    protected function getOptions(): array
    {
        return [
            new InputOption('email', 'e', InputOption::VALUE_OPTIONAL, 'Set email'),
            new InputOption('name', null, InputOption::VALUE_OPTIONAL, 'Set name'),
            new InputOption('password', 'p', InputOption::VALUE_OPTIONAL, 'Set password (Is not secure)'),
            new InputOption('generate', 'g', InputOption::VALUE_NONE, 'Autogenerate password'),
        ];
    }
}
